In [2]:
import pandas as pd
import matplotlib as plt
from matplotlib.colors import ListedColormap
import seaborn as sns

In [3]:
file = 'stack-overflow-developer-survey-2022\\survey_results_public.csv'

In [4]:
data_frame = pd.read_csv(file)

In [5]:
data_frame.head(5)

ResponseId                                         MainBranch  \
0           1                                      None of these   
1           2                     I am a developer by profession   
2           3  I am not primarily a developer, but I write co...   
3           4                     I am a developer by profession   
4           5                     I am a developer by profession   

            Employment                            RemoteWork  \
0                  NaN                                   NaN   
1  Employed, full-time                          Fully remote   
2  Employed, full-time  Hybrid (some remote, some in-person)   
3  Employed, full-time                          Fully remote   
4  Employed, full-time  Hybrid (some remote, some in-person)   

                           CodingActivities  \
0                                       NaN   
1  Hobby;Contribute to open-source projects   
2                                     Hobby   
3              I don’t code outside of work   
4                                     Hobby   

                                           EdLevel  \
0                                              NaN   
1                                              NaN   
2  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

                                           LearnCode  \
0                                                NaN   
1                                                NaN   
2  Books / Physical media;Friend or family member...   
3  Books / Physical media;School (i.e., Universit...   
4  Other online resources (e.g., videos, blogs, f...   

                                     LearnCodeOnline LearnCodeCoursesCert  \
0                                                NaN                  NaN   
1                                                NaN                  NaN   
2  Technical documentation;Blogs;Programming Game...                  NaN   
3                                                NaN                  NaN   
4  Technical documentation;Blogs;Stack Overflow;O...                  NaN   

  YearsCode  ... TimeSearching TimeAnswering Onboarding ProfessionalTech  \
0       NaN  ...           NaN           NaN        NaN              NaN   
1       NaN  ...           NaN           NaN        NaN              NaN   
2        14  ...           NaN           NaN        NaN              NaN   
3        20  ...           NaN           NaN        NaN              NaN   
4         8  ...           NaN           NaN        NaN              NaN   

  TrueFalse_1 TrueFalse_2 TrueFalse_3           SurveyLength  \
0         NaN         NaN         NaN                    NaN   
1         NaN         NaN         NaN               Too long   
2         NaN         NaN         NaN  Appropriate in length   
3         NaN         NaN         NaN  Appropriate in length   
4         NaN         NaN         NaN               Too long   

                   SurveyEase ConvertedCompYearly  
0                         NaN                 NaN  
1                   Difficult                 NaN  
2  Neither easy nor difficult             40205.0  
3                        Easy            215232.0  
4                        Easy                 NaN  

[5 rows x 79 columns]

In [6]:
data_frame.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'Country', 'Currency',
       'CompTotal', 'CompFreq', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysProfessional use',
       'OpSysPersonal use', 'VersionControlSystem', 'VCInteraction',
       'VCHostingPersonal use', 'VCHostingProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackSyncHaveWork

In [7]:
data_frame['Gender'] = data_frame['Gender'].fillna(data_frame['Gender'].mode()[0])
developer_data = data_frame[data_frame['MainBranch'] == 'I am a developer by profession']

In [8]:
total_developers = len(developer_data)
men_developers = len(developer_data[developer_data['Gender'] == 'Man'])
women_developers = len(developer_data[developer_data['Gender'] == 'Woman'])
print("Number of developer",total_developers)
print("Number of Mens working as developer",men_developers)
print("Number of Womens working as developer",women_developers)

Number of developer 53507
Number of Mens working as developer 49403
Number of Womens working as developer 2381


In [9]:
print('Percentage of the Men developers',(men_developers * 100) /total_developers)
print('Percentage of the woMen developers',(women_developers * 100) /total_developers)

Percentage of the Men developers 92.32997551722204
Percentage of the woMen developers 4.4498850617676196


In [10]:
data_frame.Country.value_counts()

United States of America                                13543
India                                                    6639
Germany                                                  5395
United Kingdom of Great Britain and Northern Ireland     4190
Canada                                                   2490
                                                        ...  
Monaco                                                      1
Djibouti                                                    1
Seychelles                                                  1
Solomon Islands                                             1
Saint Kitts and Nevis                                       1
Name: Country, Length: 180, dtype: int64

# Paid country

In [11]:
country_data = data_frame[data_frame['Country'] == 'Pakistan']

In [12]:
country_data.head()

ResponseId                      MainBranch           Employment  \
916          917  I am a developer by profession  Employed, full-time   
1198        1199           I am learning to code   Student, full-time   
1390        1391  I am a developer by profession  Employed, full-time   
2917        2918  I am a developer by profession  Employed, full-time   
3044        3045  I am a developer by profession  Employed, full-time   

                                RemoteWork  \
916                           Fully remote   
1198                                   NaN   
1390                          Fully remote   
2917                        Full in-person   
3044  Hybrid (some remote, some in-person)   

                                       CodingActivities  \
916                       Hobby;Freelance/contract work   
1198                                                NaN   
1390  Hobby;Contribute to open-source projects;Boots...   
2917  Hobby;Contribute to open-source projects;Boots...   
3044                                              Hobby   

                                                EdLevel  \
916        Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
1198  Some college/university study without earning ...   
1390       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2917       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
3044       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

                                              LearnCode  \
916   Books / Physical media;Other online resources ...   
1198            School (i.e., University, College, etc)   
1390  Other online resources (e.g., videos, blogs, f...   
2917  Books / Physical media;Other online resources ...   
3044  Other online resources (e.g., videos, blogs, f...   

                                        LearnCodeOnline  \
916   Technical documentation;Blogs;Written Tutorial...   
1198                                                NaN   
1390  Technical documentation;Blogs;Written Tutorial...   
2917  Technical documentation;Blogs;Stack Overflow;V...   
3044  Technical documentation;Blogs;Written Tutorial...   

                        LearnCodeCoursesCert YearsCode  ...  \
916                        Udemy;Pluralsight         3  ...   
1198                                     NaN         3  ...   
1390                                     NaN         5  ...   
2917                                     NaN        15  ...   
3044  Coursera;Udemy;Pluralsight;edX;Udacity         4  ...   

            TimeSearching         TimeAnswering     Onboarding  \
916                   NaN                   NaN            NaN   
1198                  NaN                   NaN            NaN   
1390                  NaN                   NaN            NaN   
2917  15-30 minutes a day  60-120 minutes a day  Somewhat long   
3044  30-60 minutes a day   15-30 minutes a day     Just right   

                                       ProfessionalTech TrueFalse_1  \
916                                                 NaN         NaN   
1198                                                NaN         NaN   
1390                                                NaN         NaN   
2917  DevOps function;Continuous integration (CI) an...         Yes   
3044  Continuous integration (CI) and (more often) c...          No   

     TrueFalse_2 TrueFalse_3           SurveyLength  \
916          NaN         NaN  Appropriate in length   
1198         NaN         NaN  Appropriate in length   
1390         NaN         NaN               Too long   
2917          No         Yes               Too long   
3044         Yes          No               Too long   

                      SurveyEase ConvertedCompYearly  
916   Neither easy nor difficult              8976.0  
1198                        Easy                 NaN  
1390  Neither easy nor difficult             30000.0  
2917                        Easy             20952.0  
3044                        Easy              4308.0  

[5 ro

In [13]:
country_data["Currency"].unique()

array(['PKR\tPakistani rupee', nan, 'USD\tUnited States dollar',
       'PGK\tPapua New Guinean kina', 'SAR\tSaudi Arabian riyal',
       'AED United Arab Emirates dirham', 'GBP\tPound sterling',
       'CAD\tCanadian dollar', 'AUD\tAustralian dollar',
       'EUR European Euro'], dtype=object)

In [14]:
country_data.CompTotal.mean()

343960.0847457627

In [15]:
country_data["CompTotal"].unique()

array([1.5000e+05,        nan, 2.5000e+03, 3.5000e+05, 7.2000e+04,
       1.0000e+05, 3.0000e+05, 1.9000e+05, 7.0000e+04, 6.0000e+04,
       5.7200e+06, 2.0000e+05, 3.2000e+05, 1.3000e+05, 8.0000e+04,
       4.0000e+05, 4.5000e+04, 8.5000e+04, 3.5000e+04, 2.5000e+06,
       5.0000e+05, 1.8000e+05, 7.5000e+04, 7.0000e+05, 3.7000e+05,
       1.6000e+03, 2.3000e+05, 3.5000e+06, 5.0000e+06, 0.0000e+00,
       1.2500e+05, 1.1000e+06, 1.1000e+05, 6.0000e+01, 1.6000e+06,
       5.5000e+05, 1.2000e+05, 1.7500e+05, 1.5000e+03, 6.0000e+02,
       5.0000e+04, 2.5000e+04, 1.5000e+02, 1.4500e+05, 3.5000e+03,
       6.0000e+05, 7.0000e+02, 1.0000e+07, 5.0000e+03, 9.8000e+04,
       2.4000e+05, 9.7500e+02, 3.5000e+02, 9.0000e+04, 1.1500e+05,
       1.6000e+05, 1.2000e+03, 1.2600e+05, 4.0700e+05, 5.5000e+04,
       1.5000e+04, 3.0000e+04, 2.5000e+05, 1.2000e+06, 4.0000e+04,
       1.0000e+03, 6.8000e+03, 1.7000e+04, 1.3000e+03, 1.3500e+05,
       1.0000e+06, 3.0000e+01, 4.5000e+02, 4.8000e+05, 1.4100e

In [16]:
data_frame["YearsCode"].value_counts()

10                    5217
5                     5193
6                     4651
4                     4480
7                     4237
8                     4227
3                     4122
2                     3351
12                    2995
15                    2962
20                    2659
9                     2581
11                    1819
14                    1811
13                    1624
25                    1582
1                     1566
Less than 1 year      1413
16                    1406
30                    1330
22                    1176
18                    1150
17                    1080
40                     777
24                     752
35                     742
23                     644
19                     563
26                     489
27                     485
21                     483
28                     425
32                     371
38                     288
37                     277
34                     241
36                     236
3

In [17]:
country_data.groupby(['Country','CompTotal'], as_index=False)['CompFreq'].value_counts()

Country   CompTotal CompFreq  count
0    Pakistan         0.0  Monthly      1
1    Pakistan        30.0  Monthly      1
2    Pakistan        60.0  Monthly      1
3    Pakistan       150.0  Monthly      1
4    Pakistan       350.0  Monthly      1
..        ...         ...      ...    ...
118  Pakistan   5000000.0   Yearly      1
119  Pakistan   5720000.0   Yearly      1
120  Pakistan   6000000.0   Yearly      1
121  Pakistan   9000000.0   Yearly      1
122  Pakistan  10000000.0   Yearly      1

[123 rows x 4 columns]

In [18]:
filter = country_data["Currency"]=='PKR\tPakistani rupee'
country_data.where(filter)

ResponseId                      MainBranch           Employment  \
916         917.0  I am a developer by profession  Employed, full-time   
1198          NaN                             NaN                  NaN   
1390          NaN                             NaN                  NaN   
2917       2918.0  I am a developer by profession  Employed, full-time   
3044       3045.0  I am a developer by profession  Employed, full-time   
...           ...                             ...                  ...   
72824     72825.0  I am a developer by profession  Employed, full-time   
72868     72869.0  I am a developer by profession  Employed, full-time   
72908     72909.0  I am a developer by profession  Employed, full-time   
72937         NaN                             NaN                  NaN   
73028     73029.0  I am a developer by profession  Employed, full-time   

                                 RemoteWork  \
916                            Fully remote   
1198                                    NaN   
1390                                    NaN   
2917                         Full in-person   
3044   Hybrid (some remote, some in-person)   
...                                     ...   
72824  Hybrid (some remote, some in-person)   
72868                          Fully remote   
72908                          Fully remote   
72937                                   NaN   
73028  Hybrid (some remote, some in-person)   

                                        CodingActivities  \
916                        Hobby;Freelance/contract work   
1198                                                 NaN   
1390                                                 NaN   
2917   Hobby;Contribute to open-source projects;Boots...   
3044                                               Hobby   
...                                                  ...   
72824                            Freelance/contract work   
72868                      Hobby;Freelance/contract work   
72908                                              Hobby   
72937                                                NaN   
73028                                              Hobby   

                                               EdLevel  \
916       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
1198                                               NaN   
1390                                               NaN   
2917      Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
3044      Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
...                                                ...   
72824     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
72868     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
72908  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
72937                                              NaN   
73028  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   

                                               LearnCode  \
916    Books / Physical media;Other online resources ...   
1198                                                 NaN   
1390                                                 NaN   
2917   Books / Physical media;Other online resources ...   
3044   Other online resources (e.g., videos, blogs, f...   
...                                                  ...   
72824  Books / Physical media;Friend or family member...   
72868  Other online resources (e.g., videos, blogs, f...   
72908  Other online resources (e.g., videos, blogs, f...   
72937                                                NaN   
73028  Books / Physical media;Other online resources ...   

                                         LearnCodeOnline  \
916    Technical documentation;Blogs;Written Tutorial...   
1198                                                 NaN   
1390                                                 NaN   
2917   Technical documentation;Blogs;Stack Overflow;V...   
3044   Technical documentation;Blogs;Written Tutorial...   
...                                                  .

# seleary perdiction

In [98]:
df = data_frame[["Country", "EdLevel", "YearsCodePro", "Employment", "ConvertedCompYearly"]]
df = df.rename({"ConvertedCompYearly": "Salary"}, axis=1)
df.head()

Country  \
0                                                NaN   
1                                             Canada   
2  United Kingdom of Great Britain and Northern I...   
3                                             Israel   
4                           United States of America   

                                           EdLevel YearsCodePro  \
0                                              NaN          NaN   
1                                              NaN          NaN   
2  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            5   
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)           17   
4     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            3   

            Employment    Salary  
0                  NaN       NaN  
1  Employed, full-time       NaN  
2  Employed, full-time   40205.0  
3  Employed, full-time  215232.0  
4  Employed, full-time       NaN

In [99]:
df=df[df['Salary'].notnull()]

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38071 entries, 2 to 73121
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       38071 non-null  object 
 1   EdLevel       38054 non-null  object 
 2   YearsCodePro  37935 non-null  object 
 3   Employment    38067 non-null  object 
 4   Salary        38071 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.7+ MB


In [101]:
df=df.dropna()
df.isna().sum()

Country         0
EdLevel         0
YearsCodePro    0
Employment      0
Salary          0
dtype: int64

In [102]:
df.Employment.unique()

array(['Employed, full-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed',
       'Independent contractor, freelancer, or self-employed',
       'Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Employed, part-time', 'I prefer not to say',
       'Independent contractor, freelancer, or self-employed;Retired',
       'Retired', 'Employed, part-time;Retired',
       'Employed, full-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Retired'],
      dtype=object)

In [103]:
df=df[df['Employment']=='Employed, full-time']
df=df.drop('Employment',axis=1)

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31382 entries, 2 to 73121
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       31382 non-null  object 
 1   EdLevel       31382 non-null  object 
 2   YearsCodePro  31382 non-null  object 
 3   Salary        31382 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.2+ MB


In [106]:
df['Country'].value_counts()

United States of America                                7858
Germany                                                 2382
United Kingdom of Great Britain and Northern Ireland    2341
India                                                   1869
Canada                                                  1249
                                                        ... 
Haiti                                                      1
Zambia                                                     1
Suriname                                                   1
Somalia                                                    1
Seychelles                                                 1
Name: Country, Length: 155, dtype: int64

In [107]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [108]:
country_map = shorten_categories(df.Country.value_counts(), 400)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

Other                                                   8643
United States of America                                7858
Germany                                                 2382
United Kingdom of Great Britain and Northern Ireland    2341
India                                                   1869
Canada                                                  1249
France                                                  1126
Brazil                                                  1014
Spain                                                    858
Netherlands                                              701
Australia                                                700
Italy                                                    667
Poland                                                   572
Sweden                                                   561
Russian Federation                                       425
Switzerland                                              416
Name: Country, dtype: in

In [110]:
df["YearsCodePro"].unique()

array(['5', '17', '6', '2', '4', '10', '22', '20', '9', '14', '21', '15',
       '3', '25', '7', '8', '12', '19', '24', '1', '11', '23', '45',
       'Less than 1 year', '18', '37', '46', '13', '32', '40', '27', '28',
       '16', '31', '26', '30', '34', '35', '42', '38', '36', '39', '29',
       '41', '33', '48', '44', '43', 'More than 50 years', '47', '49',
       '50'], dtype=object)

In [111]:
def clean_experience(x):
    if x ==  'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [112]:
df["EdLevel"].unique()

array(['Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Something else', 'Associate degree (A.A., A.S., etc.)',
       'Some college/university study without earning a degree',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'Primary/elementary school'], dtype=object)

In [113]:
def clean_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if 'Master’s degree' in x:
        return 'Master’s degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post grad'
    return 'Less than a Bachelors'

df['EdLevel'] = df['EdLevel'].apply(clean_education)

In [114]:
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df["EdLevel"].unique()
#le.classes_

array([2, 0, 1, 3])

In [115]:
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df["Country"].unique()

array([14,  8,  7, 15,  6,  2,  4,  9,  3,  1, 12, 11,  5, 13,  0, 10])

In [116]:
X = df.drop("Salary", axis=1)
y = df["Salary"]

In [117]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

In [118]:
y_pred = linear_reg.predict(X)

In [119]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))

In [121]:
# country, edlevel, yearscode
X = np.array([["United States of America", 'Master’s degree', 15 ]])
X

array([['United States of America', 'Master’s degree', '15']],
      dtype='<U24')

In [122]:
X[:, 0] = le_country.transform(X[:,0])
X[:, 1] = le_education.transform(X[:,1])
X = X.astype(float)
X

array([[15.,  2., 15.]])

In [124]:
y_pred = linear_reg.predict(X)
y_pred

D:\Users\dlision\miniconda3\envs\ML\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([296467.10282834])

In [126]:
import pickle
data = {"model": linear_reg, "le_country": le_country, "le_education": le_education}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_country = data["le_country"]
le_education = data["le_education"]

In [127]:
y_pred = regressor_loaded.predict(X)
y_pred

D:\Users\dlision\miniconda3\envs\ML\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([296467.10282834])